spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MarcelloCQ/gmcq-microservices-config.git
          default-label: cert
          search-paths: specific/properties/{application}
  application:
    name: taxation-service
