server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MarcelloCQ/gmcq-microservices-config.git
          clone-on-start: true
          search-paths: specific/properties/{application}
